version: '3'

services:
  web:
      build:
            context: ../..
            dockerfile: Dockerfile
      ports:
            - "8080:80"
      volumes:
            - .:/app/
      links:
            - php
  php:
      build:
            context: ../..
            dockerfile: ../php/Dockerfile
      volumes:
            - .:/app/